language: python
python:
  - "3.6"
  - "3.8"
matrix:
  include:
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
install:
  python setup.py install
script:
  python setup.py test
